import React from "react";

export default function TermsAndConditions() {
  return (
    <div className="max-w-4xl mx-auto p-6 pt-16 bg-white shadow-md rounded-md my-12">
      <h1 className="text-3xl font-bold mb-6">Terms & Conditions</h1>

      <p className="mb-4">
        This document is an electronic record in terms of  Information Technology Act, 2000   and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the  Information Technology Act, 2000  . This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>
      <p className="mb-4">
        This document is published in accordance with the provisions of  Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011   that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <span className="font-mono">www.uandinaturals.com</span> ('Website'), including the related mobile site and mobile application (hereinafter referred to as ' Platform  ').
      </p>
      <p className="mb-4">
        Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, ' Services  '). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
      </p>
      <p className="mb-4 font-semibold">
        For the purpose of these Terms of Use, wherever the context so requires ‘you’, 'your' or ‘user’ shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
      </p>
      <p className="mb-6 uppercase font-bold">
        Accessing, browsing or otherwise using the Platform indicates your agreement to all the terms and conditions under these Terms of Use, so please read the Terms of Use carefully before proceeding.
      </p>

      <ol className="list-decimal list-inside space-y-3 text-justify">
        <li>You agree to provide true, accurate and complete information during and after registration and be responsible for all acts done through your registered account on the Platform.</li>
        <li>Neither we nor any third parties provide any warranty or guarantee regarding accuracy, timeliness, performance, completeness or suitability of information and materials offered on this website or Services for any specific purpose.</li>
        <li>Your use of Services and Platform is at your own risk and discretion; we are not liable for any damages arising out of your use.</li>
        <li>Contents of the Platform and Services are proprietary; you will not claim intellectual property rights on them. This includes design, layout, graphics, etc.</li>
        <li>Unauthorized use may lead to actions against you as per Terms of Use and applicable laws.</li>
        <li>You agree to pay charges associated with availing Services.</li>
        <li>You agree not to use Platform or Services for unlawful, illegal, or forbidden purposes under Indian or local laws.</li>
        <li>The Website and Services may contain links to third-party websites governed by those websites' terms and privacy policies.</li>
        <li>Initiating a transaction availing Services forms a legally binding contract with Platform Owner.</li>
        <li>You shall indemnify and hold harmless Platform Owner and affiliates from any claims or penalties due to your breach of these Terms.</li>
        <li>Neither party is liable for failure to perform due to force majeure events.</li>
        <li>These Terms and any related disputes are governed by the laws of India.</li>
        <li>Disputes are subject to exclusive jurisdiction of courts in Coimbatore and Tamil Nadu.</li>
        <li>All communications regarding these Terms must be directed to us via contact info on this website.</li>
      </ol>
    </div>
  );
}
